name: Build -> Test

on:
  push:
    branches-ignore:
      - main
      - next
      - alpha
      - beta
      - '*.x*'
  pull_request:
    branches:
      - main
      - next
      - alpha
      - beta
      - '*.x*'

jobs:
  test:
    name: Test -> Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Track main
        run: git branch --track main origin/main || echo "Already done"

      - name: 'Derive appropriate SHAs for base and head for `nx affected` commands'
        uses: nrwl/nx-set-shas@v3

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Setup LTS Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: |
          RUN=CI npm run build-affected-libs

      - name: Test
        run: |
          RUN=CI npm run test-affected-libs
