name: 'size'
on:
  pull_request:
    branches:
      - main
      - next
      - alpha
      - beta
      - '*.x*'
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - uses: andresz1/size-limit-action@v1
        with:
          build_script: signallingjs:build:size-limit
          github_token: ${{ secrets.GITHUB_TOKEN }}
